### ISSUE TITLE
Installer Task fails with "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed."

### ISSUE THREAD

**Issue by Lexcess** [Caphyon/advinst-vsts-tool#2]
As per the title when using the task on either a private or public build agent we get the message:

`The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance. `

The full log for the task is as follows:

```log
 ##[section]Starting: Use Advanced Installer 14.5.1
 ==============================================================================
Task         : Advanced Installer Tool Installer
Description  : Acquires a specific version of Advanced Installer from internet or the tools cache and adds it to the PATH. Use this task to install Advanced Installer for subsequent tasks
Version      : 1.0.5
Author       : Caphyon
Help         : 
==============================================================================
Checking if a cached copy exists for this version...
Cache does not contains this Advanced Installer version. Will be downloaded and installed.
Downloading Advanced Installer. URL: https://www.advancedinstaller.com/downloads/14.5.1/advinst.msi
Downloading: https://www.advancedinstaller.com/downloads/14.5.1/advinst.msi
Extracting Advanced Installer
The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance. 
##[error]Failed to extract Advanced Installer.
##[section]Finishing: Use Advanced Installer 14.5.1
```
If it helps, on the private agent the Build Agent runs under the Network Service account (but that is something we can't really change). 

One other weird thing to note. The error message is displayed with every an unprintable unicode character inserted after every normal character i.e. a sample directly from the log it looks like:

`� �I�n�s�t�a�l�l�e�r� �S�e�r�v�i�c�e� �c�o�u�l�d�`

I think that might just be a red herring though.

Is there something incorrect in our setup?

**Comment by burcadoruciprian** [comment]
Hi,
Is it a hosted or local agent. I have managed to obtain an error (although not this one ) on a Hosted VS2017 agent. Is this your scenario?

Thanks

**Comment by Lexcess** [comment]
As mentioned in the first line, we see the same behaviour on both Private and Hosted agents.

Edit: actually that was a mistake - we are seeing different errors. I'll get a clean copy of the hosted agent error.

**Comment by burcadoruciprian** [comment]
I have release a new version of the extension which should fix the errors on the hosted agents. Please try it and let me know.

**Comment by Lexcess** [comment]
We reinstalled and saw a licensing error on the hosted agent, we think that might be on our end and will investigate. We still have the same issue on private agents as before.

**Comment by burcadoruciprian** [comment]
What OS do you have on the private agents?

**Comment by Lexcess** [comment]
@burcadoruciprian We have a fully patched version of Windows Server 2016.

If it helps here are the roles and features:

- File and Storage Service Role
- WoW64 Support Feature
- .Net Framework 3.5 Feature
- .Net Framework 4.6 Features
- Windows PowerShell Features

**Comment by burcadoruciprian** [comment]
You get the error because the agent runs under NetworkService account which has very limited privileges.
Windows Installer service which is needed to deploy  advinst cannot be accessed. Unfortunately there is no workaround at this time. (If you exclude changing the agent account)
